[global]

# By default, Streamlit checks if the Python watchdog module is available
# and, if not, prints a warning asking for you to install it. The watchdog
# module is not required, it's just an optimization. If you want to suppress
# this warning, set to True.
# showWarningOnDirectExecution = True

# Configure the ability to share
showErrorDetails = true


[server]

# List of folders that should not be watched for changes. This impacts both
# "Run on Save" and @st.cache.
# watcherType = "watchdog"
# folderWatchBlacklist = []

# Change the type of file watcher used by Streamlit, or turn it off
# completely.
# watcherType = "poll"

# Symmetric key used to produce signed cookies. If deploying on multiple replicas,
# this should be set to the same value across all replicas to ensure they all
# share the same secret.
# cookieSecret = 

# If false, will attempt to open a browser window on start.
headless = false

# Automatically rerun script when the file is modified.
runOnSave = true

# The address where the server will listen for client and browser connections.
# Use this if you want to bind the server to a specific address.
address = "localhost"

# The port where the server will listen for client and browser connections.
port = 8501

# The base path for the URL where Streamlit should be reachable from.
baseUrlPath = ""

# Enables support for Cross-Origin Resource Sharing (CORS) protection, for added security.
enableCORS = false

# Enables support for Cross-Site Request Forgery (XSRF) protection, for added security.
enableXsrfProtection = true


[browser]

# Internet address where users should point their browsers in order to
# connect to the app. Can be IP address or DNS name and path.
# serverAddress = "localhost"

# Whether to send usage statistics to Streamlit.
gatherUsageStats = false

# Port where users should point their browsers in order to connect to the
# app. This can differ from server.port in certain scenarios.
serverPort = 8501


[theme]

# Primary accent color for interactive elements.
primaryColor = "#76B900"

# Background color for the main content area.
backgroundColor = "#FFFFFF"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#F0F2F6"

# Color used for almost all text.
textColor = "#262730"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
font = "sans serif"
